### ISSUE TITLE
Get badge from main-branch workflow

### ISSUE THREAD

**Issue by RichtersFinger** [RichtersFinger/uniquipy#10]
See [this](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-branch-parameter) and add rule
```
on:
  push:
    branches:
      - master
```
to actions-yaml
